----------------------------------------------------------------------
-- Project 17: onest Brand
----------------------------------------------------------------------
INSERT INTO public.projects (name, description, is_private, owner_id)
VALUES ('onest Brand', '', false, uid) RETURNING id INTO pid;

INSERT INTO public.tasks (title, section, due, priority, progress, project_id, created_by, sort_order) VALUES
('June PR: Action', 'Detail', '2026-06-01', '', '', pid, uid, 1),
('May PR: Action', 'Detail', '2026-05-01', '', '', pid, uid, 2),
('April PR: Action', 'Detail', '2026-04-01', '', '', pid, uid, 3),
('PR/KOLs Nov&Dec''25', 'Detail', '2025-12-26', '', 'Done', pid, uid, 4),
('KOLs Visiting: October', 'Detail', '2025-10-31', '', 'Done', pid, uid, 5),
('Store set up', 'Detail', NULL, '', 'Done', pid, uid, 6),
('Loft Eyes', 'Detail', NULL, '', 'Done', pid, uid, 7),
('Ecotopia (Paragon)', 'Detail', NULL, '', 'Done', pid, uid, 8),
('onest x BEHIND THE BRAND', 'NPD', '2025-11-29', '', 'Done', pid, uid, 9),
('Holiday Set | Self Care Set (Festive box set)', 'NPD', '2026-02-02', '', 'Done', pid, uid, 10),
('Home Goods | Kindness Tote Bag', 'NPD', '2025-12-04', '', 'Done', pid, uid, 11),
('Festive Decorative Bag', 'NPD', '2025-11-20', '', 'Done', pid, uid, 12),
('Alipay payment', 'Meeting Agenda', '2025-08-18', '', 'Done', pid, uid, 13),
('ลำดับขั้นตอนการออกสินค้า เพื่อไม่ให้มีปัญหาตอนผลิตจริง', 'Meeting Agenda', '2025-06-04', '', 'Done', pid, uid, 14),
('หาวิธีการกรอกขวด 8 ml ให้ฝ่ายผลิตทำงานง่าย (ใช้เครื่องบรรจุของเหลวของSVเครื่องใหม่))', 'Meeting Agenda', NULL, '', 'Done', pid, uid, 15),
('กล่องขนส่ง Starter Set ให้ลูกค้าที่สั่งผ่านlineOA', 'Meeting Agenda', '2025-06-05', '', 'Done', pid, uid, 16),
('Starter Set ของถึงร้านทรงวาด 28/05/25', 'Meeting Agenda', '2025-05-28', '', 'Done', pid, uid, 17),
('NPD | Set 7 Home Spray', 'Meeting Agenda', '2025-06-07', '', 'Done', pid, uid, 18),
('NPD | Home Spray 100 mL', 'Meeting Agenda', '2025-06-07', '', 'Done', pid, uid, 19),
('ทดสอบขนส่งGift Set Kitchen+Gift Set Hand Wash', 'Meeting Agenda', '2025-02-26', '', 'Done', pid, uid, 20),
('ทดสอบกลิ่น FOAMING HAND WASH (Neroli Garden)', 'Meeting Agenda', '2025-03-28', '', 'Done', pid, uid, 21),
('ทดสอบกลิ่น FOAMING HAND WASH (Serene Tea)', 'Meeting Agenda', '2025-03-14', '', 'Done', pid, uid, 22),
('ทดสอบกลิ่น FOAMING HAND WASH (Charlene Rose)', 'Meeting Agenda', '2025-03-14', '', 'Done', pid, uid, 23),
('ทดสอบกลิ่นFABRIC FAGRANCE (Wild Mint)', 'Meeting Agenda', '2025-02-26', '', 'Done', pid, uid, 24),
('ทดสอบกลิ่นFABRIC FAGRANCE (Cotton Musk)', 'Meeting Agenda', '2025-02-26', '', 'Done', pid, uid, 25),
('ทดสอบกลิ่นDISH SOAP (Pine Forest)', 'Meeting Agenda', '2025-02-28', '', 'Done', pid, uid, 26),
('จัดเตรียมเอกสารสำหรับการตรวจประเมินประจำปี', 'Meeting Agenda', '2025-02-28', '', 'Done', pid, uid, 27),
('Recheck ว่าสบู่กดยากเกินไปหรือเปล่า (from Amp)', 'Meeting Agenda', '2025-01-31', '', 'Done', pid, uid, 28),
('Test ว่า Dishwash กลิ่นติดจานนานเกินไปหรือเปล่า', 'Meeting Agenda', '2025-01-31', '', 'Done', pid, uid, 29),
('Test Bloom & Blossoms กับดอกไม้ใส่แจกัน', 'Meeting Agenda', '2025-01-31', '', 'Done', pid, uid, 30),
('Revise COG ให้ถูกต้อง', 'Meeting Agenda', '2025-01-30', 'High', 'Done', pid, uid, 31),
('Key Agenda for overall weekly', 'Meeting Agenda', NULL, '', '', pid, uid, 32),
('RD weekly meeting 6/03/25', 'Meeting Agenda', NULL, '', 'Done', pid, uid, 33),
('Weekly Meeting Agenda 15 May', 'Meeting Agenda', '2025-05-15', '', 'Done', pid, uid, 34),
('Weekly Meeting Agenda 22 May', 'Meeting Agenda', NULL, '', 'Done', pid, uid, 35),
('Weekly Meeting Agenda 29 May', 'Meeting Agenda', NULL, '', 'Done', pid, uid, 36),
('Weekly Meeting Agenda 5 June', 'Meeting Agenda', NULL, '', 'Done', pid, uid, 37),
('Weekly Meeting Agenda 12 June', 'Meeting Agenda', NULL, '', 'Done', pid, uid, 38),
('Weekly Meeting Agenda 26 June', 'Meeting Agenda', NULL, '', 'Done', pid, uid, 39),
('Weekly Meeting Agenda 3 July', 'Meeting Agenda', NULL, '', 'Done', pid, uid, 40),
('Weekly Meeting Agenda 17 July', 'Meeting Agenda', NULL, '', '', pid, uid, 41),
('Follow up gae mink เรื่องป้าย', 'New Store Projects', '2025-10-09', '', 'Done', pid, uid, 42),
('Central Dusit Park 4 Sep 2025', 'New Store Projects', NULL, '', 'Done', pid, uid, 43),
('Talad Noi 24 Oct 2025', 'New Store Projects', NULL, '', 'Done', pid, uid, 44),
('Siam Discovery 1 Feb 2026', 'New Store Projects', NULL, '', 'Done', pid, uid, 45),
('(Cancel) Soul Songwat 20 Feb 2026', 'New Store Projects', NULL, '', '', pid, uid, 46),
('Promotional Signage Implementation', 'Retail', '2026-04-09', '', '', pid, uid, 47),
('Find out review app china & groom Review System หน้าร้าน', 'Retail', NULL, '', '', pid, uid, 48),
('Siam Discovery Improvement', 'Retail', '2026-03-16', '', '', pid, uid, 49),
('(onest) รายการของเก่าที่ต้องซ่อมหรือเปลี่ยน Song Wat', 'Retail', '2026-03-16', '', '', pid, uid, 50),
('เอาป้ายทรงวาดที่แกะออกภายในร้านกลับมาทั้งหมด', 'Retail', '2025-10-17', '', 'Done', pid, uid, 51),
('รูปข้างร้านทรงวาดหลุด', 'Retail', '2025-10-17', '', 'Done', pid, uid, 52),
('Final new layout Dusit', 'Retail', '2025-10-03', '', 'Done', pid, uid, 53),
('ขอมิเตอร์น้ำไฟทรงวาด', 'Retail', '2025-10-31', '', 'Done', pid, uid, 54),
('Final เรื่องถุง (สี กับ เนื้อถุง)', 'Retail', '2025-08-15', '', 'Done', pid, uid, 55),
('ลูกค้าค่อนข้างสับสนเรื่อง Ambient Parfum', 'Retail', '2025-07-31', '', 'Done', pid, uid, 56),
('ขอให้ป้ายโปสเตอร์ทั้งหมด กลับมาติดที่ร้านภายในวันศุกร์ 15/8 อย่างช้าที่สุด', 'Retail', '2025-08-15', '', 'Done', pid, uid, 57),
('Set up ระบบ recruit & training PC', 'Retail', '2025-09-30', '', 'Done', pid, uid, 58),
('ป้าย handwash set (ทดแทน kitchen set หมด ไม่มีสต๊อค)', 'Retail', NULL, '', 'Done', pid, uid, 59),
('สติ๊กเกอร โลโก้ที่แปะถุง ให้ซัพตัดมาเลย', 'Retail', NULL, '', 'Done', pid, uid, 60),
('โซน ambient parfum  อุปกรณ์ให้ลูกค้าเทสต์กลิ่น (เป็นขวดแบบเดิมก้ได้ค่ะ)', 'Retail', '2025-06-27', '', 'Done', pid, uid, 61),
('ตรงโซน ambient parfum  อยากได้ป้ายเล็กๆที่บอกชื่อกลิ่นค่ะ น้องๆบอกว่าลูกค้ามองไม่เห็น', 'Retail', NULL, '', 'Done', pid, uid, 62),
('นามบัตรติดไว้ที่ร้าน กรณี B2B', 'Retail', '2025-09-15', '', 'Done', pid, uid, 63),
('ซื้อด้ามจับเปลี่ยนประตูหน้าร้าน พี่เจริญจะเข้ามาเปลี่ยนให้', 'Retail', '2025-07-30', '', 'Done', pid, uid, 64),
('เติมสินค้าขายร้านทรงวาด', 'Retail', '2025-05-28', '', 'Done', pid, uid, 65),
('[onest store] แก้เกมเนื่องจากเลื่อนวันเปิดร้าน', 'Retail', NULL, '', 'Done', pid, uid, 66),
('[onest store] คำบนกระจกใหญ่ ซ้าย ขวา', 'Retail', '2025-05-27', '', 'Done', pid, uid, 67),
('[onest store] AW Invitation card', 'Retail', NULL, '', 'Done', pid, uid, 68),
('[onest store] in-store 9 cards', 'Retail', '2025-04-10', 'Medium', 'Done', pid, uid, 69),
('[onest store] AW Invitation card', 'Retail', '2025-04-11', '', 'Done', pid, uid, 70),
('[onest store] เปิดเบอร์และอีเมลสำหรับสมัคร K+Shop', 'Retail', '2025-04-18', '', 'Done', pid, uid, 71),
('รายการเบิกผลิตภัณฑ์FG + ถุงบรรจุภัณฑ์', 'Retail', '2025-04-18', '', 'Done', pid, uid, 72),
('[onest store] KOL Phase 2', 'Retail', '2025-04-09', '', 'Done', pid, uid, 73),
('Grand Timeline', 'Retail', NULL, '', '', pid, uid, 74),
('ปรับเวลา 1) จันทร์ - ศุกร์ เปิด 11 AM - 19 PM 2) เพิ่มสองกะ ปิด 4 ทุ่ม เสาร์ อาทิตย์ (11-22 PM) -> รอหาคนได้ก่อน (ฝากพี่จอยกับเฟิสคุยแผนต่อ)', 'Retail', '2025-09-01', '', 'Done', pid, uid, 75),
('Repackaging - Discovery Set', 'Retail', '2026-01-01', '', 'Done', pid, uid, 76),
('กระดาษเทสต์กลิ่นที่ร้าน', 'Retail', NULL, '', 'Done', pid, uid, 77),
('หาพนักงานสำหรับเปิดร้าน', 'Retail', '2025-03-14', '', 'Done', pid, uid, 78),
('Training พนักงาน', 'Retail', '2025-04-24', '', 'Done', pid, uid, 79),
('Final Uniform พนักงานหน้าร้าน + สั่งผลิต', 'Retail', '2025-02-28', '', 'Done', pid, uid, 80),
('ส่งแบบเพื่อเคลียร์พื้นที่ก่อน', 'Retail', '2025-02-25', '', 'Done', pid, uid, 81),
('Scent Design for Store', 'Retail', '2025-03-29', '', 'Done', pid, uid, 82),
('ระบบขายของหน้าร้าน (POS)', 'Retail', '2025-04-25', '', 'Done', pid, uid, 83),
('Graphic poster หาพนักงานหน้าร้าน', 'Retail', '2025-02-14', '', 'Done', pid, uid, 84),
('Design Scent for the store?', 'Retail', NULL, '', 'Done', pid, uid, 85),
('Ref ideas for experience design', 'Retail', NULL, '', 'Done', pid, uid, 86),
('1st round location plan for survey', 'Retail', '2025-01-14', '', 'Done', pid, uid, 87),
('Final คนออกแบบ', 'Retail', '2025-01-31', '', 'Done', pid, uid, 88),
('Spray ทดลองกลิ่น หรือ หัวน้ำหอมของแต่กลิ่น', 'Retail', NULL, '', 'Done', pid, uid, 89),
('ปรับมุมCCTV มุมเเคชเชียร์', 'Retail', NULL, '', 'Done', pid, uid, 90),
('เติมป้าย และของ vanich 🏠', 'B2B | Event | Collab', '2025-10-09', '', 'Done', pid, uid, 91),
('Contact friend friend (emporium) เพื่อวางขาย', 'B2B | Event | Collab', '2025-10-01', '', 'Done', pid, uid, 92),
('onest VIP list', 'B2B | Event | Collab', NULL, '', '', pid, uid, 93),
('Onest B2B pipeline', 'B2B | Event | Collab', NULL, '', '', pid, uid, 94),
('Onest Office Product Display', 'B2B | Event | Collab', '2025-03-17', '', 'Done', pid, uid, 95),
('Project Proposal ให้สถานที่', 'B2B | Event | Collab', '2025-02-28', 'Medium', 'Done', pid, uid, 96),
('เช็ครายละเอียดบ้านและสวน', 'B2B | Event | Collab', '2025-01-16', '', 'Done', pid, uid, 97),
('Event List', 'B2B | Event | Collab', NULL, '', 'Not Started', pid, uid, 98),
('สั่งป้ายชื่อบริษัท Mimetta & Mimetta Living', 'B2B | Event | Collab', '2025-07-18', '', 'Done', pid, uid, 99),
('onest Shelf (Consignment)', 'B2B | Event | Collab', NULL, '', '', pid, uid, 100),
('Ecotopia', 'B2B | Event | Collab', NULL, '', 'Done', pid, uid, 101),
('First aid', 'B2B | Event | Collab', NULL, '', 'Done', pid, uid, 102),
('onest Booth', 'B2B | Event | Collab', NULL, '', '', pid, uid, 103),
('All about you', 'B2B | Event | Collab', NULL, '', 'Done', pid, uid, 104),
('Sponsor', 'B2B | Event | Collab', NULL, '', '', pid, uid, 105),
('B2B Contact for gifting product', 'B2B | Event | Collab', NULL, '', '', pid, uid, 106),
('เตรียมของสำหรับให้พี่พอทไปแจกในงานสัมมนา 5 มีนา', 'B2B | Event | Collab', '2025-02-26', 'Medium', 'Done', pid, uid, 107),
('onest Special Set', 'All Marketing', '2025-08-07', '', 'Done', pid, uid, 108),
('Promotion offline', 'All Marketing', '2025-08-13', '', 'Done', pid, uid, 109),
('CRM', 'All Marketing', '2025-08-14', '', 'Done', pid, uid, 110),
('Cross boarder', 'All Marketing', '2025-11-11', '', 'Done', pid, uid, 111),
('Whole Sale - Rate card', 'All Marketing', NULL, '', '', pid, uid, 112),
('Line Rich Menu Update', 'All Marketing', NULL, '', 'Done', pid, uid, 113),
('Spotify', 'All Marketing', NULL, '', 'Done', pid, uid, 114),
('Video Content (E-commerce)', 'All Marketing', NULL, '', 'Done', pid, uid, 115),
('กระจกถ่ายรูปหน้าร้าน', 'All Marketing', NULL, '', 'Done', pid, uid, 116),
('Brand Deck', 'All Marketing', '2025-10-23', '', 'Done', pid, uid, 117),
('(Soul Songwat) Store Concept Brief', 'All Marketing', '2025-09-17', '', 'Done', pid, uid, 118),
('Merchandise 2026', 'All Marketing', NULL, '', '', pid, uid, 119),
('(Emporium) Store Concept Brief', 'All Marketing', '2025-09-17', '', 'Done', pid, uid, 120),
('เริ่มวางโบว์ชัวในกล่องสินค้า', 'All Marketing', NULL, '', 'Done', pid, uid, 121),
('SD LED - Siam Discovery', 'All Marketing', NULL, '', '', pid, uid, 122),
('Brochure ใส่กล่องขายออนไลน์', 'All Marketing', '2025-11-01', '', 'Done', pid, uid, 123),
('ดินสอพอง', 'All Marketing', NULL, '', '', pid, uid, 124),
('Songwat Week - GWP Ambient Parfum', 'All Marketing', '2025-11-17', '', 'Done', pid, uid, 125),
('GWP ถุงหอม', 'All Marketing', NULL, '', '', pid, uid, 126),
('Huge Bag Spec from MKT & Design', 'All Marketing', '2026-02-05', '', 'Done', pid, uid, 127),
('AW for E-commerce [NPD+Gifting]', 'All Marketing', '2025-06-13', 'Medium', 'Done', pid, uid, 128),
('Photoshoot Home Spray May 2025', 'All Marketing', '2025-05-28', 'High', 'Done', pid, uid, 129),
('Brief Product Catalog', 'All Marketing', '2025-01-31', 'High', 'Done', pid, uid, 130),
('Brand Company Profile', 'All Marketing', '2025-01-31', 'Medium', 'Done', pid, uid, 131),
('onest x Furawadesu', 'All Marketing', '2025-02-16', 'High', 'Done', pid, uid, 132),
('Product Display Design', 'All Marketing', '2025-02-06', '', 'Done', pid, uid, 133),
('ทำ ACC GOAL & RM ของ ONEST ให้เสร็จวันนี้', 'All Marketing', '2025-02-24', '', 'Done', pid, uid, 134),
('Brief E-commerce', 'All Marketing', '2025-01-17', 'High', 'Done', pid, uid, 135),
('Scent Card Design', 'All Marketing', NULL, 'Low', 'Done', pid, uid, 136),
('ขอ Official ทุกช่องทาง', 'All Marketing', '2025-03-31', 'Low', 'Done', pid, uid, 137),
('Brand Advertorial (P''Amp)', 'All Marketing', NULL, '', 'Done', pid, uid, 138),
('Adhoc onest x plantae?', 'All Marketing', NULL, '', 'Done', pid, uid, 139),
('TikTok: Build Unit Sold', 'PR', '2026-03-02', 'High', 'In Progress', pid, uid, 140),
('TikTok Revenue – January 2026', 'PR', '2026-01-31', 'High', 'Done', pid, uid, 141),
('KOLs: Contents and PR of January 2026', 'PR', '2026-01-31', 'High', 'Done', pid, uid, 142),
('onest Fam: Pre-Brand Ambassador Program', 'PR', '2026-06-01', '', 'Not Started', pid, uid, 143),
('Free Media: Neighbors and Friends', 'PR', '2026-01-27', 'Medium', 'Done', pid, uid, 144),
('PR Free Media ongoing', 'PR', '2026-03-26', '', 'Done', pid, uid, 145),
('Gifting to Sector Leaders list', 'PR', '2026-01-27', '', 'Done', pid, uid, 146),
('TikTok Revenue – February 2026', 'PR', '2026-02-26', 'High', 'Done', pid, uid, 147),
('Stock Management report', 'PR', '2026-01-26', 'High', 'Done', pid, uid, 148),
('KOLs - Onest', 'PR', NULL, 'High', 'Done', pid, uid, 149),
('KOL/Influencer', 'PR', NULL, '', 'Done', pid, uid, 150),
('หาร้านพันธมิตร', 'PR', NULL, '', 'Done', pid, uid, 151),
('Test ส่งสินค้าให้ KOL', 'PR', NULL, '', 'Done', pid, uid, 152),
('Plan for furawadesu x onest', 'PR', NULL, '', 'Done', pid, uid, 153),
('ส่งแมส KOL กทม 9 คน', 'PR', NULL, 'High', 'Done', pid, uid, 154),
('ส่งของ KOL 5 คน', 'PR', '2025-03-04', 'High', 'Done', pid, uid, 155),
('สรุป Tracking งาน KOL', 'PR', '2025-03-05', 'Medium', 'Done', pid, uid, 156),
('แพลน KOL For Q2', 'PR', '2025-03-07', '', 'Done', pid, uid, 157),
('KOL มาหน้าร้าน เซทแรก', 'PR', '2025-05-06', 'High', 'Done', pid, uid, 158),
('KOL มาหน้าร้านทรงวาด Set 2', 'PR', '2025-05-18', 'High', 'Done', pid, uid, 159),
('KOL มาหน้าร้านทรงวาด Set 3', 'PR', NULL, '', 'Done', pid, uid, 160),
('KOLs  Thank you card', 'Design', NULL, 'Medium', 'Done', pid, uid, 161),
('Body Cleanser / Nourishing Creme', 'Design', NULL, '', '', pid, uid, 162),
('ป้ายเเจ้งขั้นต่ำบัตรเครดิตและบัตรเดบิต รับขั้นต่ำ 500 บาท วางเเคชเชียร์หน้าร้านทรงวาด', 'Design', '2025-05-30', '', 'Done', pid, uid, 163),
('สติ๊กเกอร์"สินค้าแจกฟรี ห้ามจำหน่าย" ติดสินค้าทุกตัวที่ใช้สำหรับแจก (สรุปใช้สำเร็จรูปค่ะ)', 'Design', '2025-06-04', '', 'Done', pid, uid, 164),
('แก้ ฉลาก Home Spray เป็น Ambient Parfum', 'Design', '2025-05-22', 'High', 'Done', pid, uid, 165),
('IG Highlight Design', 'Design', '2025-02-19', 'High', 'Done', pid, uid, 166),
('Brief / Set up E-commerce (Laz/TT/Line/Shopee)', 'Design', '2025-01-22', 'High', 'Done', pid, uid, 167),
('GWP Fabric Fragrance', 'Design', '2025-01-28', '', 'Done', pid, uid, 168),
('กล่อง Delivery', 'Design', NULL, '', 'Done', pid, uid, 169),
('แก้ฉลาก Hand Soap เป็น 300 mL (สำหรับพร้อมขาย 11 นี้)', 'Design', '2025-02-06', 'High', 'Done', pid, uid, 170),
('Office Product Display (ติดตั้งเรียบร้อย)', 'Design', '2025-02-17', '', 'Done', pid, uid, 171),
('Small Giftset | HW+FF', 'Design', NULL, '', '', pid, uid, 172),
('AW ใบกำกับภาษี ออกย้อนหลังไม่ได้ (Adhoc Thumbnail on Shopee/Laz/TT)', 'Design', '2025-04-08', '', '', pid, uid, 173),
('Barcodes แยกสำหรับแปะก้นขวด', 'Design', '2026-01-21', '', '', pid, uid, 174),
('Relabel with Barcode', 'Design', NULL, '', '', pid, uid, 175),
('ป้ายสแกนคิวอาร์โค้ดสมัครMembershipหน้าสาขาทรงวาด 1 ใบ + อะคลีลิค', 'Design', '2025-12-01', '', 'Done', pid, uid, 176),
('Holiday Set Final', 'Design', '2025-08-14', '', 'Done', pid, uid, 177),
('Songwat week: Gifting ให้ลูกค้า 400 pcs.', 'Design', '2025-11-14', '', 'Done', pid, uid, 178),
('ตกแต่งหน้าร้าน ตีม white christmas', 'Design', '2025-11-20', '', 'Done', pid, uid, 179),
('กล่องพัสดุขนนส่งแบบสกรีน (ราคา+ไซส์)', 'Procurement', '2025-06-13', '', 'Done', pid, uid, 180),
('สั่งซื้อ bubble', 'Procurement', '2025-07-10', '', 'Done', pid, uid, 181),
('Cashflow planning', 'Procurement', '2025-07-11', '', 'Done', pid, uid, 182),
('Cross Boarder Shop', 'E-Commerce', NULL, '', '', pid, uid, 183),
('Set-up E-commerce ระบบหลังบ้าน', 'E-Commerce', '2025-01-15', 'Medium', 'Done', pid, uid, 184),
('แจกพนักงาน 2 ชิ้นผ่าน Shopee (หลังติดตั้ง Office Display เสร็จ)', 'E-Commerce', '2025-02-28', '', 'Done', pid, uid, 185),
('ยื่นเรื่องให้ platform เป็นตัวแทนหักและนำส่งภาษีหัก ณ ที่จ่าย', 'E-Commerce', '2025-03-03', '', 'Done', pid, uid, 186),
('Factory Meeting WK52// 22.12.2025', 'Factory', NULL, '', '', pid, uid, 187),
('Factory Meeting WK51// 15.12.2025', 'Factory', NULL, '', '', pid, uid, 188),
('Factory Meeting WK50// 8.12.2025', 'Factory', NULL, '', '', pid, uid, 189),
('Factory Meeting WK49// 1.12.2025', 'Factory', NULL, '', '', pid, uid, 190),
('Factory Meeting WK47// 17.11.2025', 'Factory', NULL, '', '', pid, uid, 191),
('Factory Meeting WK46// 10.11.2025', 'Factory', NULL, '', '', pid, uid, 192),
('Factory Meeting WK45// 03.11.2025', 'Factory', NULL, '', '', pid, uid, 193),
('Factory Meeting WK44// 27.10.2025', 'Factory', NULL, '', '', pid, uid, 194),
('Factory Meeting WK43// 20.10.2025', 'Factory', NULL, '', '', pid, uid, 195),
('Factory Meeting WK41// 06.10.2025', 'Factory', NULL, '', '', pid, uid, 196),
('Factory Meeting WK40// 29.09.2025', 'Factory', NULL, '', '', pid, uid, 197),
('Factory Meeting WK39// 22.09.2025', 'Factory', NULL, '', '', pid, uid, 198),
('Factory Meeting WK38// 15.09.2025', 'Factory', NULL, '', '', pid, uid, 199),
('Factory Meeting WK37// 08.09.2025', 'Factory', NULL, '', '', pid, uid, 200),
('Factory Meeting WK36// 01.09.2025', 'Factory', NULL, '', '', pid, uid, 201),
('Factory Meeting WK33// 14.08.2025', 'Factory', NULL, '', '', pid, uid, 202),
('Factory Meeting WK32// 08.08.2025', 'Factory', NULL, '', '', pid, uid, 203),
('Factory Meeting WK31// 1.08.2025', 'Factory', NULL, '', '', pid, uid, 204),
('Factory Meeting WK29// 18.07.2025', 'Factory', NULL, '', '', pid, uid, 205),
('Factory Meeting WK28// 11.07.2025', 'Factory', NULL, '', '', pid, uid, 206),
('Factory Meeting WK27// 04.07.2025', 'Factory', NULL, '', '', pid, uid, 207),
('Factory Meeting WK26// 27.06.2025', 'Factory', NULL, '', '', pid, uid, 208),
('Operations (Brain storm) Note', 'Factory', NULL, '', '', pid, uid, 209),
('KPI onest operation Sep-Dec 2025', 'Factory', NULL, '', '', pid, uid, 210),
('CCTV', 'Production', '2025-10-31', '', 'Done', pid, uid, 211),
('Waste Sticker 100 ml parfum -> new % Waste?', 'Production', '2025-06-16', '', 'Done', pid, uid, 212),
('SOP เอกสาร ขั้นตอนการผสมสูตร', 'Production', '2025-03-14', '', '', pid, uid, 213),
('แบบบันทึกข้อมูลการผลิตของสินค้า (ฟอร์มเอิร์ธ)', 'Production', '2025-03-14', '', '', pid, uid, 214),
('การรับวัตถุดิบเข้า (GR) ตรวจสอบน้ำหนัก/ตรวจสอบวัตถุดิบให้ตรงตามสเปค', 'Production', '2025-03-14', '', '', pid, uid, 215),
('การจัดเก็บวัตถุดิบ ให้เหมาะสมกับวัตถุดิบนั้นๆ', 'Production', '2025-03-14', '', '', pid, uid, 216),
('สอบเทียบปริมาณต่อหน่วยปริมาตรของFabric', 'Production', '2025-02-27', '', 'Done', pid, uid, 217),
('สอบเทียบปริมาณต่อหน่วยปริมาตรของ Bloom & Blossom', 'Production', '2025-02-24', '', 'Done', pid, uid, 218),
('กรอกข้อมูล budget ของ operation โรงงาน', 'Production', '2025-02-25', '', 'Done', pid, uid, 219),
('กำหนดพื้นที่จัดเก็บตัวอย่างสินค้า (เซ็ตอุณหภูมิ 3 แบบ)', 'Production', '2025-03-14', '', '', pid, uid, 220),
('ผลิตสินค้าOnest first lot = 300 pcs./sku', 'Production', '2025-02-03', '', 'Done', pid, uid, 221),
('Raw material ถึงโรงงาน', 'Production', '2025-01-31', '', 'Done', pid, uid, 222),
('กล่อง delivery ถึงโรงงาน', 'Production', '2025-01-31', '', 'Done', pid, uid, 223),
('Update stock card', 'Production', '2025-02-03', '', 'Done', pid, uid, 224),
('Report to accounting team', 'Production', '2025-02-28', '', 'Done', pid, uid, 225),
('พิจารณาสมัคร GS1 บาร์โค้ด ในนาม บ.มีเมตตา', 'Production', NULL, '', 'Done', pid, uid, 226),
('Bloom & Blossoms size 10 ml (แถม14ก.พ.)', 'Production', '2025-02-10', '', 'Done', pid, uid, 227),
('สอบเทียบปริมาณต่อหน่วยปริมาตรของ Dish soap', 'Production', '2025-03-10', '', 'Done', pid, uid, 228),
('สอบเทียบปริมาณต่อหน่วยปริมาตรของ Surface Cleaner', 'Production', '2025-02-25', '', 'Done', pid, uid, 229),
('สอบเทียบปริมาณต่อหน่วยปริมาตรของ Hand wash Neroli', 'Production', '2025-02-27', '', 'Done', pid, uid, 230),
('แพลนการผลิตของเข้าทรงวาด', 'Production', NULL, '', '', pid, uid, 231),
('แผนการใช้เอกสารจริงในกระบวนการทั้งหมดของโรงงาน', 'Production', NULL, '', '', pid, uid, 232),
('เริ่มใช้งานเครื่องติดสติกเกอร์และเครื่องยิงวันที่', 'Production', NULL, '', '', pid, uid, 233),
('onest: ทดสอบ stability test (เก็บทดสอบเอง)', 'QMS', NULL, '', '', pid, uid, 234),
('List Award หรือ Certificate ที่น่าขอ', 'QMS', NULL, 'Low', '', pid, uid, 235),
('Set up ระบบ Traceability (การตรวจสอบย้อนกลับ)', 'QMS', '2025-08-15', '', 'Done', pid, uid, 236),
('Maintenance planing', 'QMS', '2025-08-04', '', 'Done', pid, uid, 237),
('งานแม่บ้าน', 'QMS', NULL, '', 'Done', pid, uid, 238),
('onest: ทดสอบ delivery เองก่อน 1 รอบ', 'QMS', '2025-02-08', 'High', 'Done', pid, uid, 239),
('Test ลูกพลับมีสี ฉีดใส่เสื้อผ้าหรือเฟอร์สีขาว', 'QMS', '2025-01-29', '', 'Done', pid, uid, 240),
('ตรวจวิเคราะห์น้ำเสียตามประกาศ ประจำปี 68', 'RA', '2025-10-31', '', 'Done', pid, uid, 241),
('onest: certificate for products', 'RA', NULL, '', '', pid, uid, 242),
('ขึ้นทะเบียนผู้ประกอบการส่งออก onest', 'RA', '2026-02-28', '', '', pid, uid, 243),
('ขึ้นทะเบียน วอ 3', 'RA', '2025-04-30', '', 'Done', pid, uid, 244),
('จด Trade mark "onest"', 'RA', '2026-12-31', '', '', pid, uid, 245),
('ขอใบอนุญาตผลิต วอ.3', 'RA', '2025-12-31', '', '', pid, uid, 246),
('อ.ย', 'RA', NULL, '', '', pid, uid, 247),
('สบู่ & diffuser แยกช้้น', 'Customer Complain Report (CCR)', '2025-10-09', '', 'Done', pid, uid, 248),
('Recheck กลิ่น CL & NG ไม่ติดมือเหมือนเดิม', 'Customer Complain Report (CCR)', '2025-10-16', '', 'Done', pid, uid, 249),
('ฟอร์มรับเรื่องข้อร้องเรียนผลิตภัณฑ์', 'Customer Complain Report (CCR)', NULL, '', '', pid, uid, 250),
('Surface cleaner ทำให้โต๊ะด่าง > เจอ 2 คน', 'Customer Complain Report (CCR)', NULL, '', '', pid, uid, 251),
('ถุงสีดำขาดตอนหิ้วไปให้ลูกค้า (อาจจะถือไปหลายถุง) > เปลี่ยนซัพแล้ว', 'Customer Complain Report (CCR)', NULL, '', 'Done', pid, uid, 252),
('Ambient Parfum', 'Customer Complain Report (CCR)', NULL, '', '', pid, uid, 253),
('สติ๊กเกอร์พองขวดHW/SF100ml', 'Customer Complain Report (CCR)', '2025-06-04', '', 'Done', pid, uid, 254),
('ลูกค้าใช้ Hand wash แล้วแพ้ ระคายเคือง > เจอ 1 คน', 'Customer Complain Report (CCR)', '2025-05-26', '', '', pid, uid, 255),
('Project : Satin veil Body Lotion', 'Sourcing & Procurement', NULL, 'Medium', 'In Progress', pid, uid, 256),
('Project : Hand cream', 'Sourcing & Procurement', NULL, 'Medium', 'In Progress', pid, uid, 257);
